stages:
  01a_build_global_dataset:
    cmd: python scripts/script_01_build_datasets.py global
    deps:
      - data/slack_1/raw
      - scripts/script_01_build_datasets.py
    outs:
      - data/slack_1/global/slack_1_global.tsv
  01b_build_processed_datasets:
    cmd: python scripts/script_01_build_datasets.py processed
    deps:
      - data/slack_1/global/slack_1_global.tsv
      - scripts/script_01_build_datasets.py
    outs:
      - data/slack_1/processed
  04a_prepare_CompAIRR_data:
    cmd: python scripts/script_04a_prepare_CompAIRR_data.py
    deps:
      - data/slack_1/processed
      - scripts/script_04a_prepare_CompAIRR_data.py
    outs:
      - data/CompAIRR/prepared_data
  04b_CompAIRR:
    cmd: bash scripts/script_04b_CompAIRR.sh
    deps:
      - data/CompAIRR/prepared_data/AIRR.tsv
      - data/CompAIRR/prepared_data/AIRR_global_repertoire.tsv
      - scripts/script_04b_CompAIRR.sh
    outs:
      - data/CompAIRR/results
  05_SN10_closedset_binary_interpretability:
    cmd: python scripts/script_05_SN10_closedset_binary_interpretability.py
    deps:
      - data/slack_1/processed
      - scripts/script_05_SN10_closedset_binary_interpretability.py
    params:
      - 05_SN10_closedset_binary_interpretability.ag_neg
      - 05_SN10_closedset_binary_interpretability.ag_pos
      - 05_SN10_closedset_binary_interpretability.epochs
      - 05_SN10_closedset_binary_interpretability.learning_rate
    outs:
      - data/SN10_closedset_binary_interpretability/
  05b_all_SN10_closedset_binary_interpretability:
    cmd: python scripts/script_05b_all_SN10_closedset_binary_interpretability.py
    deps:
      - data/slack_1/processed
      - scripts/script_05b_all_SN10_closedset_binary_interpretability.py
    params:
      - 05_SN10_closedset_binary_interpretability.epochs
      - 05_SN10_closedset_binary_interpretability.learning_rate
    outs:
      - data/SN10_closedset_binary_interpretability_all
        #  - data/nco_mlflow_runs
  06_SN10_openset_NDB1:
    cmd: python scripts/script_06_SN10_openset_NDB1.py
    deps:
      - data/slack_1/processed
      - scripts/script_06_SN10_openset_NDB1.py
    params:
      - 06_SN10_openset_NDB1.experiment_id
      - 06_SN10_openset_NDB1.run_name
      - 06_SN10_openset_NDB1.num_processes
      - 06_SN10_openset_NDB1.epochs
      - 06_SN10_openset_NDB1.learning_rate
    # outs:
      # - data/nco_mlflow_runs
  06b_SN10_NDB1_crossval:
    cmd: python scripts/script_06b_SN10_NDB1_crossval.py
    deps:
      - data/slack_1/processed
      - scripts/script_06b_SN10_NDB1_crossval.py
    params:
      - 06b_SN10_NDB1_crossval.experiment_id
      - 06b_SN10_NDB1_crossval.run_name
      - 06b_SN10_NDB1_crossval.num_processes
      - 06b_SN10_NDB1_crossval.epochs_val
      - 06b_SN10_NDB1_crossval.epochs_train
      - 06b_SN10_NDB1_crossval.learning_rate_range
      - 06b_SN10_NDB1_crossval.batch_sizes
      - 06b_SN10_NDB1_crossval.momentum_range
      - 06b_SN10_NDB1_crossval.weight_decays
      - 06b_SN10_NDB1_crossval.n_trials
    # outs:
      # - data/nco_mlflow_runs
  script_07_SN10_openset_NDBK:
    cmd: python scripts/script_07_SN10_openset_NDBK.py
    deps:
      - data/slack_1/processed
      - scripts/script_07_SN10_openset_NDBK.py
    params:
      - 07_SN10_openset_NDBK.experiment_id
      - 07_SN10_openset_NDBK.run_name
      - 06_SN10_openset_NDB1.num_processes
      - 06_SN10_openset_NDB1.epochs
      - 06_SN10_openset_NDB1.learning_rate
    outs:
      # - data/nco_mlflow_runs