stages:
  04a_prepare_CompAIRR_data:
    cmd: python scripts/script_04a_prepare_CompAIRR_data.py
    deps:
    - data/globals/slack_1_global.tsv
    - scripts/script_04a_prepare_CompAIRR_data.py
    outs:
    - data/CompAIRR/prepared_data
  04b_CompAIRR:
    cmd: bash scripts/script_04b_CompAIRR.sh
    deps:
    - data/CompAIRR/prepared_data/AIRR.tsv
    - data/CompAIRR/prepared_data/AIRR_global_repertoire.tsv
    - scripts/script_04b_CompAIRR.sh
    outs:
    - data/CompAIRR/results
  05_SN10_closedset_binary_interpretability:
    cmd: python scripts/script_05_SN10_closedset_binary_interpretability.py
    deps:
    - data/globals/slack_1_global.tsv
    - scripts/script_05_SN10_closedset_binary_interpretability.py
    params:
    - 05_SN10_closedset_binary_interpretability.ag_neg
    - 05_SN10_closedset_binary_interpretability.ag_pos
    - 05_SN10_closedset_binary_interpretability.epochs
    - 05_SN10_closedset_binary_interpretability.learning_rate
    outs:
    - data/SN10_closedset_binary_interpretability/
  05b_all_SN10_closedset_binary_interpretability:
    cmd: python scripts/script_05b_all_SN10_closedset_binary_interpretability.py
    deps:
    - data/globals/slack_1_global.tsv
    - scripts/script_05b_all_SN10_closedset_binary_interpretability.py
    params:
    - 05_SN10_closedset_binary_interpretability.epochs
    - 05_SN10_closedset_binary_interpretability.learning_rate
    outs:
    - data/SN10_closedset_binary_interpretability_all
  06_SN10_openset_NDB1:
    cmd: python scripts/script_06_SN10_openset_NDB1.py
    deps:
      - data/globals/slack_1_global.tsv
      - scripts/script_06_SN10_openset_NDB1.py
    params:
      - 06_SN10_openset_NDB1.experiment_id
      - 06_SN10_openset_NDB1.run_name
      - 06_SN10_openset_NDB1.num_processes
      - 06_SN10_openset_NDB1.epochs
      - 06_SN10_openset_NDB1.learning_rate
    # outs:  # are logged with mlflow
