name: ab-negative-training
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pandas
  - seaborn
  - more-itertools
  - jupyterlab
  - umap-learn
  - pytorch 
  - torchvision 
  - torchaudio 
  - captum
  - cudatoolkit=10.2
  - optuna
  - pip
  - pip:
      - dvc[gdrive]==2.10.2
      - dash==2.3.1
      - nptyping
      - immuneML==2.2.2
      - docopt
      - upsetplot
      - scikit-learn
      - joypy
      - networkx==2.6.3
      - mlflow
      - pyfarmhash
