name: ab-negative-training
channels:
  - defaults
dependencies:
  - python=3.8
  - pandas
  - seaborn
  - more-itertools
  - pip
  - jupyterlab
  - pip:
      - dvc[gdrive]
      - dash==2.3.1
      - nptyping
      - docopt
      - upsetplot
      - dask
      - git+https://github.com/uio-bmi/immuneML.git
