name: nco
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python
  - pandas
  - seaborn
  - more-itertools
  - jupyterlab
  # - umap-learn
  - pytorch 
  - torchvision 
  - torchaudio 
  - captum
<<<<<<< HEAD
=======
  - pytdc
  - rdkit=2023.03.1
>>>>>>> fe2426a (Add small molecules and epistasis code)
  # - cudatoolkit=10.2
  - optuna
  - sphinx
  - jsonnet
  - pip
  - pip:
      #- dvc[gdrive]==2.10.2
      - dash==2.3.1
      - nptyping
      # - docopt
      - upsetplot
      - dask
      # - git+https://github.com/uio-bmi/immuneML.git
      - scikit-learn
      # - scikit-image
      - statsmodels
      - joypy
      - networkx
      - mlflow
      #- pyfarmhashy
      #- pre-commit
      - setuptools==57.5.0
      - joblib
      - dovpanda
      - nbconvert
      - nbdev
      # - bio-embeddings[all]
      # - modisco
      # - tfmodisco-lite
      - logomaker
      - docker
      - pykeops
      - geomloss
      - wget
      - Bio
      # - cmake
      # - tensorflow
      # - multicoretsne
      - tqdm
      # - img2pdf
      - black