name: ab-negative-training
channels:
  - defaults
dependencies:
  - python=3.8
  - pandas
  - seaborn
  - more-itertools
  - pip
  - jupyterlab
  - pip:
      - dvc[gdrive]==2.10.2
      - dash==2.3.1
      - nptyping
      - immuneML==2.2.2
      - docopt
      - upsetplot
