05_SN10_closedset_binary_interpretability:
  ag_pos: "3VRL"
  ag_neg: "1WEJ"
  learning_rate: 0.01
  epochs: 30
05b_all_SN10_closedset_binary_interpretability:
  experiment_id: 1
  run_name: "run_5"
  num_processes: 20
  learning_rate: 0.01
  epochs: 30
06_SN10_openset_NDB1:
  experiment_id: 2
  run_name: "run_1"
  num_processes: 20
  epochs: 50
  learning_rate: 0.01
06b_SN10_NDB1_crossval:
  experiment_id: 3
  run_name: "run_1"
  num_processes: 20
  epochs_val: 25
  epochs_train: 50
  learning_rate_range: [0.001, 1]
  batch_sizes: [128, 256, 512, 1024]
  momentum_range: [0.8, 0.99]
  weight_decays: [0, 0.00001, 0.0001, 0.001]
  n_trials: 30
