05_SN10_closedset_binary_interpretability:
  ag_pos: "3VRL"
  ag_neg: "1ADQ"
  learning_rate: 0.01
  epochs: 5
05b_all_SN10_closedset_binary_interpretability:
  experiment_id: 1
  run_name: "first_run"
  num_processes: 12
  learning_rate: 0.01
  epochs: 5
