05_SN10_closedset_binary_interpretability:
  ag_pos: "3VRL"
  ag_neg: "1ADQ"
  learning_rate: 0.01
  epochs: 5
05b_all_SN10_closedset_binary_interpretability:
  experiment_id: 1
  run_name: "run_2"
  num_processes: 20
  learning_rate: 0.01
  epochs: 20
06_SN10_openset_NDB1:
  experiment_id: 2
  run_name: "DEV"
  num_processes: 20
  epochs: 30
  learning_rate: 0.01
