channels:
- conda-forge
dependencies:
- python=3.8.16
- pip<=22.3.1
- pip:
  - mlflow<3,>=2.1
  - astunparse==1.6.3
  - captum==0.5.0
  - cffi==1.15.1
  - cloudpickle==2.2.1
  - defusedxml==0.7.1
  - dill==0.3.6
  - ipython==8.7.0
  - negativeclassoptimization==0.1.0
  - psutil==5.9.0
  - pyfarmhash==0.3.2
  - torch==1.9.1
name: mlflow-env
